### ISSUE TITLE
Missing functions?

### ISSUE THREAD

**Issue by zbzhu99** [zhiyuzz/Hieararchical-IL#1]
Hi, thank you for this interesting paper, and I appreciate the rigorous analysis in your paper.

When I check the code in this repo, it seems that there are missing function definitions, such as `forward`, `backward`, or `smoothing`. I guess these codes are contained in the `Functions` directory, where you add that directory to path in your code. However, this directory has not been committed to this repo. Hope you can help me with that.

Thank you for your time.

**Comment by zhiyuzz** [comment]
My apologies, thanks for catching that! I uploaded the missing code, and it should work now.

**Comment by zbzhu99** [comment]
> My apologies, thanks for catching that! I uploaded the missing code, and it should work now.  

Thank you!
